### ISSUE TITLE
If this spec is defunct, can it be clearly marked as such?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/html-api-map#6]
Based on @jasonkiss' comment here https://github.com/w3c/aria/issues/544#issuecomment-290551078 this spec is "old and defunct". could this be made absolutely clear at the start of the document, with pointers to the new spec we should be looking at (https://w3c.github.io/html-aam/ from what i understand)?

**Comment by patrickhlauke** [comment]
i see a warning/note is present on the "latest published version" https://www.w3.org/TR/html-aapi/ but not on the editor's draft. i'd suggest porting this to the editor's draft as well...and even to this repo's readme/description

**Comment by jasonkiss** [comment]
good suggestion. 

Note added to http://rawgit.com/w3c/html-api-map/master/index.html, and also to this repo's readme.md
